services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - inventario-network

  php:
    image: php:8.2-apache
    container_name: php-container
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
    command: >
      bash -c "docker-php-ext-install mysqli && apache2-foreground"
    networks:
      - inventario-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - inventario-network

networks:
  inventario-network:
    driver: bridge
