services:
  php:
    image: php:8.2-apache
    container_name: php-container
    volumes:
      - .:/var/www/html
    ports:
      - "${PORT}:80"  # Render necesita que uses su variable PORT
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: >
      bash -c "docker-php-ext-install mysqli && apache2-foreground"
